import { Product, Order, User, Transaction, CartItem } from "@/types";
import { 
  Category, 
  ProductStatus, 
  PerfumeType, 
  Gender, 
  Longevity, 
  Sillage, 
  OrderStatus, 
  Role, 
  UserStatus, 
  TransactionStatus 
} from "../generated/prisma/client";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Mystique Oud",
    brand: "Elegant Essence",
    slug: "mystique-oud",
    category: Category.WOODY_SPICY,
    price: 185.00,
    rating: 4.9,
    reviews: 124,
    imageBg: "from-zinc-900 to-amber-950",
    description: "An exotic blend of rare oud, warm spices, and dark wood accents. Mystique Oud represents the summit of warm wood elegance, blending smooth sweetness with dark rich smoke. Perfectly suited for evening wears or intimate settings.",
    notes: ["Top: Bergamot, Pink Pepper", "Heart: Turkish Rose, Agarwood", "Base: Patchouli, Ambergris, Vetiver"],
    ingredients: "Alcohol Denat., Fragrance (Parfum), Water\\Aqua\\Eau, Linalool, Limonene, Agarwood Extract, Coumarin, Benzyl Bezoate.",
    stock: 45,
    status: ProductStatus.IN_STOCK,
    type: PerfumeType.EDP,
    gender: Gender.UNISEX,
    volume: "100 ml",
    longevity: Longevity.EIGHT_TWELVE_HOURS,
    sillage: Sillage.STRONG,
  },
  {
    id: "2",
    name: "Sylvan Bloom",
    brand: "Elegant Essence",
    slug: "sylvan-bloom",
    category: Category.FLORAL,
    price: 140.00,
    rating: 4.8,
    reviews: 98,
    imageBg: "from-emerald-900 to-teal-950",
    description: "Fresh forest moss with undertones of wild violet and green ivy. Sylvan Bloom encapsulates the freshness of a rain-soaked forest canopy in early spring. An uplifting scent suitable for daytime wear.",
    notes: ["Top: Cut Grass, Green Ivy", "Heart: Wild Violet, White Jasmine", "Base: Forest Moss, Cedarwood"],
    ingredients: "Alcohol Denat., Water\\Aqua\\Eau, Fragrance (Parfum), Benzyl Salicylate, Geraniol, Citronellol, Oakmoss Extract.",
    stock: 12,
    status: ProductStatus.LOW_STOCK,
    type: PerfumeType.EDT,
    gender: Gender.FEMALE,
    volume: "100 ml",
    longevity: Longevity.SIX_EIGHT_HOURS,
    sillage: Sillage.MEDIUM,
  },
  {
    id: "3",
    name: "Amber Velvet",
    brand: "Elegant Essence",
    slug: "amber-velvet",
    category: Category.AMBER_FLORAL,
    price: 165.00,
    rating: 4.7,
    reviews: 82,
    imageBg: "from-rose-950 to-orange-950",
    description: "Soft vanilla, warm amber crystals, and powdery cashmere musk. Amber Velvet wraps you in a comforting, powdery warmth that behaves like a second skin. Exceptionally long-lasting and rich.",
    notes: ["Top: Chilled Cardamom", "Heart: Heliotrope, Vanilla Orchid", "Base: Amber Crystals, Cashmere Musk, Sandalwood"],
    ingredients: "Alcohol Denat., Fragrance (Parfum), Water\\Aqua\\Eau, Benzyl Alcohol, Citral, Hydroxycitronellal, Limonene.",
    stock: 85,
    status: ProductStatus.IN_STOCK,
    type: PerfumeType.PARFUM,
    gender: Gender.UNISEX,
    volume: "50 ml",
    longevity: Longevity.EIGHT_TWELVE_HOURS,
    sillage: Sillage.VERY_STRONG,
  },
  {
    id: "4",
    name: "Citron Glace",
    brand: "Elegant Essence",
    slug: "citron-glace",
    category: Category.AROMATIC_FRUITY,
    price: 120.00,
    rating: 4.6,
    reviews: 64,
    imageBg: "from-yellow-900 to-lime-950",
    description: "Zesty Sicilian bergamot, chilled mint, and white cedarwood. A crisp, crystalline explosion of citrus fruits that is clean, sharp, and energizing.",
    notes: ["Top: Sicilian Bergamot, Lemon Zest", "Heart: Chilled Mint Leaves, Coriander", "Base: White Cedarwood, Musk"],
    ingredients: "Alcohol Denat., Fragrance (Parfum), Water\\Aqua\\Eau, Limonene, Linalool, Citral, Geraniol, Farnesol.",
    stock: 0,
    status: ProductStatus.OUT_OF_STOCK,
    type: PerfumeType.EDC,
    gender: Gender.MALE,
    volume: "100 ml",
    longevity: Longevity.TWO_FOUR_HOURS,
    sillage: Sillage.LIGHT,
  },
  {
    id: "5",
    name: "Oceanic Mist",
    brand: "Elegant Essence",
    slug: "oceanic-mist",
    category: Category.WOODY_AROMATIC,
    price: 135.00,
    rating: 4.9,
    reviews: 153,
    imageBg: "from-blue-950 to-indigo-950",
    description: "Crisp sea salt, ozone currents, and sun-bleached driftwood. Oceanic Mist takes you directly to the water's edge, offering an airy and crisp salty breeze.",
    notes: ["Top: Crisp Sea Salt, Red Algae", "Heart: Ocean Accord, Sage", "Base: Driftwood, Ambrette Seed"],
    ingredients: "Alcohol Denat., Water\\Aqua\\Eau, Fragrance (Parfum), Alpha-Isomethyl Ionone, Geraniol, Linalool.",
    stock: 32,
    status: ProductStatus.IN_STOCK,
    type: PerfumeType.EDT,
    gender: Gender.UNISEX,
    volume: "100 ml",
    longevity: Longevity.FOUR_SIX_HOURS,
    sillage: Sillage.MEDIUM,
  },
  {
    id: "6",
    name: "Noir Jasmine",
    brand: "Elegant Essence",
    slug: "noir-jasmine",
    category: Category.ORIENTAL_FLORAL,
    price: 195.00,
    rating: 4.9,
    reviews: 210,
    imageBg: "from-purple-950 to-zinc-950",
    description: "Night-blooming jasmine, dark patchouli, and spicy black pepper. Noir Jasmine is an intoxicating, opulent fragrance that sits beautifully on the boundary between dark spices and soft petals.",
    notes: ["Top: Black Pepper, Ginger", "Heart: Night-Blooming Jasmine, Orchid", "Base: Patchouli, Sandalwood, Vanilla"],
    ingredients: "Alcohol Denat., Fragrance (Parfum), Water\\Aqua\\Eau, Jasminum Officinale Extract, Eugenol, Benzyl Cinnamate.",
    stock: 19,
    status: ProductStatus.IN_STOCK,
    type: PerfumeType.EDP,
    gender: Gender.FEMALE,
    volume: "100 ml",
    longevity: Longevity.SIX_EIGHT_HOURS,
    sillage: Sillage.STRONG,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "EE-9283-091",
    date: "June 12, 2026",
    total: 523.80,
    status: OrderStatus.PROCESSING,
    buyerId: "user-john",
    buyer: "John Doe",
    items: [
      { name: "Mystique Oud", qty: 1, quantity: 1, volume: "100 ml", price: 185.00 },
      { name: "Amber Velvet", qty: 1, quantity: 1, volume: "50 ml", price: 165.00 },
      { name: "Oceanic Mist", qty: 1, quantity: 1, volume: "100 ml", price: 135.00 },
    ],
  },
  {
    id: "EE-8120-745",
    date: "May 28, 2026",
    total: 151.20,
    status: OrderStatus.DELIVERED,
    buyerId: "user-sarah",
    buyer: "Sarah Connor",
    items: [
      { name: "Sylvan Bloom", qty: 1, quantity: 1, volume: "100 ml", price: 140.00 },
    ],
  },
  {
    id: "EE-3049-112",
    date: "April 15, 2026",
    total: 210.60,
    status: OrderStatus.DELIVERED,
    buyerId: "user-emma",
    buyer: "Emma Watson",
    items: [
      { name: "Noir Jasmine", qty: 1, quantity: 1, volume: "100 ml", price: 195.00 },
    ],
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "user-john",
    name: "John Doe",
    email: "john.doe@example.com",
    password: "password123",
    role: Role.CUSTOMER,
    status: UserStatus.ACTIVE,
    joined: "June 10, 2026",
    phone: "+1 (555) 019-2834",
    address: "100 Luxury Avenue, Suite 400\nNew York, NY 10001",
    preference: "Woody",
  },
  {
    id: "user-sarah",
    name: "Sarah Connor",
    email: "sarah.c@sky.net",
    password: "password123",
    role: Role.CUSTOMER,
    status: UserStatus.ACTIVE,
    joined: "June 08, 2026",
  },
  {
    id: "user-admin",
    name: "Admin Chief",
    email: "chief@elegantessence.com",
    password: "adminpassword",
    role: Role.ADMIN,
    status: UserStatus.ACTIVE,
    joined: "May 01, 2026",
  },
  {
    id: "user-alex",
    name: "Alex Mercer",
    email: "mercer@gentek.org",
    password: "password123",
    role: Role.CUSTOMER,
    status: UserStatus.SUSPENDED,
    joined: "May 15, 2026",
  },
  {
    id: "user-emma",
    name: "Emma Watson",
    email: "emma.w@hogwarts.edu",
    password: "password123",
    role: Role.CUSTOMER,
    status: UserStatus.ACTIVE,
    joined: "May 20, 2026",
  },
];

export const INITIAL_CART_ITEMS: CartItem[] = [
  {
    id: "1",
    name: "Mystique Oud",
    volume: "100 ml",
    category: Category.WOODY_SPICY,
    price: 185.00,
    quantity: 1,
    imageBg: "from-zinc-900 to-amber-950",
  },
  {
    id: "3",
    name: "Amber Velvet",
    volume: "50 ml",
    category: Category.AMBER_FLORAL,
    price: 165.00,
    quantity: 1,
    imageBg: "from-rose-950 to-orange-950",
  },
  {
    id: "5",
    name: "Oceanic Mist",
    volume: "100 ml",
    category: Category.WOODY_AROMATIC,
    price: 135.00,
    quantity: 1,
    imageBg: "from-blue-950 to-indigo-950",
  },
];

export const RECENT_TRANSACTIONS: Transaction[] = [
  { id: "TXN-9018", orderId: "EE-9283-091", customer: "Sophia Martinez", date: "Just now", status: TransactionStatus.PAID, amount: 185.00 },
  { id: "TXN-8902", orderId: "EE-8120-745", customer: "Liam Johnson", date: "12 mins ago", status: TransactionStatus.PAID, amount: 305.00 },
  { id: "TXN-8843", orderId: "EE-3049-112", customer: "Emma Watson", date: "45 mins ago", status: TransactionStatus.FAILED, amount: 140.00 },
  { id: "TXN-8798", orderId: "EE-9283-091", customer: "Noah Alvi", date: "2 hours ago", status: TransactionStatus.PAID, amount: 523.80 },
];
